import { Roboto } from 'next/font/google'
import './globals.css'
import Header from './component/Header/Header'
import Footer from './component/Footer/Footer'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='p-6'>
        <body className={roboto.className}>
          <Header />
          <hr />
         {children}
         <hr />
         <Footer />
        </body>
    </html>
  )
}
